blog/urls.py
from django.urls import path
from .views import blog_post_create, blog_post_detail, BlogPostDelete, blog_post_list, BlogPostUpdate, filtered_posts
from .views import CategoryCreate, CategoryDelete, CategoryList

app_name = 'blog'

urlpatterns = [
    path('post-list/', blog_post_list, name='posts_list'),
    path('blogpost/create/', blog_post_create, name='post_creation'),
    path('blogpost/<int:pk>/delete/', BlogPostDelete.as_view(), name='post_delete'),
    path('blogpost/<int:pk>/detail/', blog_post_detail, name='post_detail'),
    path('blogpost/<int:pk>/update/', BlogPostUpdate.as_view(), name='post_update'),
    path('category/create/', CategoryCreate.as_view(), name='category_creation'),
    path('category/<int:pk>/delete/', CategoryDelete.as_view(), name='category_delete'),
    path('category-list/', CategoryList.as_view(), name='category_list'),
    path('find/<str:name>/', filtered_posts, name='filter')
]

comment/urls.py
from django.urls import path
from .views import delete_comment, update_comment
app_name = 'comment'

urlpatterns = [
    path('comment/<int:pk>/comment-update/', update_comment, name='comment_update'),
    path('comment/<int:pk>/delete/', delete_comment, name='comment_delete'),
]

core/urls.py
import notifications.urls
from django.contrib import admin
from django.urls import include, path, re_path
from core.views import Home, Contacts, Gym, Services
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^$', Home.as_view(), name='home'),
    path('palestra/', Gym.as_view(), name='gym'),
    path('servizi/', Services.as_view(), name='services'),
    path('corsi/', include('gym_course.urls')),
    path('contattaci/', Contacts.as_view(), name='contacts'),
    path('blog/', include('blog.urls')),
    path('blog/blogpost/', include('comment.urls')),
    path('user/', include('gym_user.urls')),
    path('rooms/', include('room.urls')),
    path('auth/', include('user_auth.urls')),
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),
]

"""
By doing this, Django development server can able to serve the media
files during development mode when setting  DEBUG = TRUE  in settings.py file.
"""
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

comment/models.py
from django.db import models
from blog.models import BlogPost
from gym_user.models import GymUser


class Comment(models.Model):
    post = models.ForeignKey(BlogPost, on_delete=models.CASCADE, related_name='comments')
    commenter = models.ForeignKey(GymUser, on_delete=models.CASCADE)
    content = models.TextField()
    date = models.DateField(auto_now=True)

    def __str__(self):
        return self.commenter.username + " - " + self.post.title + " - " + self.date.__str__()

    class Meta:
        verbose_name_plural = 'Commenti'

comment/forms.py
from django import forms
from django.forms import Textarea

from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']
        widgets = {
            'content': Textarea(attrs={'placeholder': 'Scrivi un commento...', 'rows': 5})
        }

comment/views.py
from django.http import HttpResponseForbidden
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, HttpResponseRedirect, reverse, get_object_or_404
from .forms import CommentForm
from .models import Comment


@login_required(login_url="user_auth:login")
def update_comment(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    if request.user.id == comment.commenter.id or request.user.is_superuser:
        if request.method == 'POST':
            form = CommentForm(request.POST, instance=comment)
            if form.is_valid():
                data = form.cleaned_data
                comment.content = data.get('content')
                comment.save()
                messages.success(request, "Messaggio modificato correttamente!")
                return HttpResponseRedirect(reverse("blog:post_detail", kwargs={'pk': comment.post.id}))
        else:
            form = CommentForm(instance=comment)
            return render(request, "comment/comment_update.html", {"comment_form": form})
    else:
        return HttpResponseForbidden(render(request, "403.html"))


@login_required(login_url="user_auth:login")
def delete_comment(request, pk):
    comment = Comment.objects.filter(pk=pk).first()
    if request.user.is_superuser or request.user.id == comment.commenter.id:
        comment.delete()
        messages.success(request, "Messaggio rimosso con successo!")
        return HttpResponseRedirect(reverse("blog:post_detail", kwargs={'pk': comment.post.id}))
    else:
        return HttpResponseForbidden(render(request, "403.html"))

templates/comment/comment_update.html
{% extends 'my-gym/base.html' %}
{% load crispy_forms_tags %}
{% block head %}
    <style>
        form {
            max-width: 75% !important;
            margin: 0 auto;
        }

        form input {
            margin: 17px 0 !important;
        }

        form label {
            display: none;
        }

    </style>
{% endblock %}
{% block content %}
    <h4 class="text-center f-sm-bold mb-5">Modifica il tuo commento:</h4>
    <form method="POST" class="text-end">
        {% csrf_token %}
        {{ comment_form|crispy }}
        <button type="submit" class="bg-transparent border-0 mt-2 me-2">
            <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18"
                 fill="currentColor"
                 class="bi bi-send" viewBox="0 0 16 16"
                 style="transform: rotate(45deg)">
                <path d="M15.854.146a.5.5 0 0 1 .11.54l-5.819 14.547a.75.75 0 0 1-1.329.124l-3.178-4.995L.643 7.184a.75.75 0 0 1 .124-1.33L15.314.037a.5.5 0 0 1 .54.11ZM6.636 10.07l2.761 4.338L14.13 2.576 6.636 10.07Zm6.787-8.201L1.591 6.602l4.339 2.76 7.494-7.493Z"/>
            </svg>
        </button>
    </form>
{% endblock %}

templates/comment/post_comments.html
{% load static %}
{% if post.comments.count == 0 %}
     <div class="container" style="position: sticky; top: 0;">
        <hr>
    </div>
    <div class="container mt-5">
        <p class="f-mid text-center">Nessun commento per questo post.</p>
    </div>
{% else %}
    <div class="container" style="position: sticky; top: 0;">
        <hr>
    </div>
    {% for comment in post.comments.all %}
        <div class="d-flex flex-row justify-content-start align-items-start pt-1"
             style="margin-bottom: 50px;">
            {% if comment.commenter.image_url %}
                <img src="{{ comment.commenter.image_url }}"
                     class="rounded-circle ms-3 me-3 mt-1" width="40" height="40" alt="msg-pic">
            {% else %}
                <img src="{% static 'img/avatar.jpg' %}"
                     class="rounded-circle ms-3 me-3 mt-1" width="40" height="40" alt="msg-pic">
            {% endif %}
            <div class="d-flex flex-column">
                <div class="text-dark bg-secondary bg-opacity-10 rounded me-5">
                    <p class="f-sm-bold ps-3 pe-3 pt-2 m-0">{{ comment.commenter.username|capfirst }}</p>
                    <p class="f-mid ps-3 pe-3 text-wrap p-2"
                       style="width: 100%;">
                        {{ comment.content }}</p>
                </div>
                <div class="d-flex flex-row justify-content-between">
                    <p class="ps-2 pt-1 f-bold c-grey"
                       style="font-size: 10px;"
                    >{{ comment.date|date:"SHORT_DATE_FORMAT" }}</p>
                    {% if request.user == comment.commenter or request.user.is_superuser %}
                        <div class="d-flex flex-row pt-1 pe-5" style="font-size: 9px;">
                            <a href="{% url 'comment:comment_update' comment.id %}"
                               class="text-secondary pb-1 f-sm-bold me-2">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                     class="bi bi-pencil" viewBox="0 0 16 16">
                                    <path d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z"/>
                                </svg>
                            </a>
                            <a href="{% url 'comment:comment_delete' comment.id %}" class="text-danger p-0 f-sm-bold ">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                     class="bi bi-trash3" viewBox="0 0 16 16">
                                    <path d="M6.5 1h3a.5.5 0 0 1 .5.5v1H6v-1a.5.5 0 0 1 .5-.5ZM11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3A1.5 1.5 0 0 0 5 1.5v1H2.506a.58.58 0 0 0-.01 0H1.5a.5.5 0 0 0 0 1h.538l.853 10.66A2 2 0 0 0 4.885 16h6.23a2 2 0 0 0 1.994-1.84l.853-10.66h.538a.5.5 0 0 0 0-1h-.995a.59.59 0 0 0-.01 0H11Zm1.958 1-.846 10.58a1 1 0 0 1-.997.92h-6.23a1 1 0 0 1-.997-.92L3.042 3.5h9.916Zm-7.487 1a.5.5 0 0 1 .528.47l.5 8.5a.5.5 0 0 1-.998.06L5 5.03a.5.5 0 0 1 .47-.53Zm5.058 0a.5.5 0 0 1 .47.53l-.5 8.5a.5.5 0 1 1-.998-.06l.5-8.5a.5.5 0 0 1 .528-.47ZM8 4.5a.5.5 0 0 1 .5.5v8.5a.5.5 0 0 1-1 0V5a.5.5 0 0 1 .5-.5Z"/>
                                </svg>
                            </a>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
    {% endfor %}
{% endif %}