blog/urls.py
from django.urls import path
from .views import blog_post_create, blog_post_detail, BlogPostDelete, blog_post_list, BlogPostUpdate, filtered_posts
from .views import CategoryCreate, CategoryDelete, CategoryList

app_name = 'blog'

urlpatterns = [
    path('post-list/', blog_post_list, name='posts_list'),
    path('blogpost/create/', blog_post_create, name='post_creation'),
    path('blogpost/<int:pk>/delete/', BlogPostDelete.as_view(), name='post_delete'),
    path('blogpost/<int:pk>/detail/', blog_post_detail, name='post_detail'),
    path('blogpost/<int:pk>/update/', BlogPostUpdate.as_view(), name='post_update'),
    path('category/create/', CategoryCreate.as_view(), name='category_creation'),
    path('category/<int:pk>/delete/', CategoryDelete.as_view(), name='category_delete'),
    path('category-list/', CategoryList.as_view(), name='category_list'),
    path('find/<str:name>/', filtered_posts, name='filter')
]

core/urls.py
import notifications.urls
from django.contrib import admin
from django.urls import include, path, re_path
from core.views import Home, Contacts, Gym, Services
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^$', Home.as_view(), name='home'),
    path('palestra/', Gym.as_view(), name='gym'),
    path('servizi/', Services.as_view(), name='services'),
    path('corsi/', include('gym_course.urls')),
    path('contattaci/', Contacts.as_view(), name='contacts'),
    path('blog/', include('blog.urls')),
    path('blog/blogpost/', include('comment.urls')),
    path('user/', include('gym_user.urls')),
    path('rooms/', include('room.urls')),
    path('auth/', include('user_auth.urls')),
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),
]

"""
By doing this, Django development server can able to serve the media
files during development mode when setting  DEBUG = TRUE  in settings.py file.
"""
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gym_course/urls.py
from django.urls import path
from .views import add_to_queue, courses_list, make_inscription, mark_as_read, unsubscribe
app_name = 'gym_course'

urlpatterns = [
    path('', courses_list, name='courses'),
    path('iscriviti/<int:course_pk>/', make_inscription, name='make_inscription'),
    path('mettiti-in-lista/<int:course_pk>/', add_to_queue, name='add_to_queue'),
    path('discriviti/<int:course_pk>/<str:to_queue>/', unsubscribe, name='unsubscribe'),
    path('mark-as-read/<int:not_slug>/', mark_as_read, name='mark_not_as_read'),
]

gym_user/urls.py
from django.urls import path
from .views import load_notification, profile_view
app_name = 'gym_user'

urlpatterns = [
    path('profile/', profile_view, name='profile'),
    path('load_notification', load_notification, name='load_notification'),

]

room/urls.py
from django.urls import path
from .views import chat, rooms

app_name = 'room'

urlpatterns = [
    path('', rooms, name='chat-rooms'),
    path('<slug:slug>/chat/', chat, name='chat'),
]

user_auth/urls.py
from django.urls import path
from .views import change_password, change_user_data, delete_user, login_user, logout_user, register
app_name = 'user_auth'

urlpatterns = [
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('register/', register, name='register'),
    path('change_password/', change_password, name='change_password'),
    path('change_user_data/', change_user_data, name='change_data'),
    path('delete_user/', delete_user, name='user_delete'),
]

templates/my-gym/base.html
{% load static %}
{% load notifications_tags %}
<!doctype html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'site.webmanifest' %}">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
          rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
          crossorigin="anonymous"
    >
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
          rel="stylesheet"
    >
    <link rel="stylesheet" type="text/css" href="{% static 'css/my-gym/base-styles.css' %}">
    {% block head %}{% endblock %}
    <title>{% block title %}{% endblock %}</title>
    <style>

    </style>
</head>

<body>

<header>
    <!--NAVBAR-->
    <nav class="navbar fixed-top navbar-expand-lg navbar-light border-bottom">
        <div class="container ">
            <a class="navbar-brand" href="{% url 'home' %}">
                <img src="{% static 'img/gym-logo.svg' %}" alt="gym logo"
                     class="d-inline-block align-text-top logo_my_gym ms-3">
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown"
                    aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown" style="position: relative;">
                <ul class="navbar-nav ms-lg-4">
                    <li class="nav-item">
                        <a class="nav-link f-mid c-black" href="{% url 'gym' %}">PALESTRA</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link f-mid c-black" href="{% url 'services' %}">SERVIZI</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link f-mid c-black" href="{% url 'gym_course:courses' %}">CORSI</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link f-mid c-black" href="{% url 'blog:posts_list' %}">BLOG</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link f-mid c-black" href="{% url 'contacts' %}">CONTATTI</a>
                    </li>
                    {% if user.is_authenticated %}
                        <div class="nav-item dropdown user-block">
                            <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle ms-3 mt-lg-3"
                               id="dropdownUser1"
                               data-bs-toggle="dropdown" aria-expanded="false">
                                {% if user.profile_image %}
                                    <img src="{{ user.image_url }}" alt="mdo" width="34" height="34"
                                         class="rounded-circle">
                                {% else %}
                                    <img src="{% static 'img/avatar.jpg' %}" class="rounded-circle " width="34"
                                         height="34">
                                {% endif %}
                            </a>
                            <ul class="dropdown-menu text-small" aria-labelledby="dropdownUser1">
                                <li><a class="dropdown-item" href="{% url 'gym_user:profile' %}">Profilo</a></li>
                                <li><a class="dropdown-item" href="{% url 'gym_course:courses' %}">Iscriviti a un
                                    corso</a>
                                </li>
                                <li><a class="dropdown-item" href="{% url 'blog:posts_list' %}">Leggi un articolo</a>
                                </li>
                                <li><a class="dropdown-item" href="{% url 'room:chat-rooms' %}">Chat</a>
                                </li>
                                <li>
                                    <hr class="dropdown-divider">
                                </li>
                                <li><a class="dropdown-item" href="{% url 'user_auth:logout' %}">Logout</a></li>
                            </ul>
                        </div>
                    {% else %}
                        <li class="nav-item mt-3 auth-button">
                            <div class="d-flex flex-column flex-lg-row justify-content-center">
                                <a type="button" class="btn btn-outline-primary f-mid me-lg-2 mb-2 mb-lg-0"
                                   href="{% url 'user_auth:login' %}">Login</a>
                                <a type="button" class="btn btn-primary f-mid" href="{% url 'user_auth:register' %}">Registrati</a>
                            </div>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    <!--/.NAVBAR-->
    <!--DJANGO MESSAGES-->
    {% if messages %}
        <section class="container-fluid messages fixed-top" style="margin-top: 90px;">
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }} alert-dismissible fade show d-flex align-items-center"
                     role="alert">
                    {% if message.tags == 'success' %}
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                             class="bi bi-check-circle-fill m-2" viewBox="0 0 16 16">
                            <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
                        </svg>
                    {% elif message.tags == 'info' %}
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                             class="bi bi-info-circle-fill m-2" viewBox="0 0 16 16">
                            <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2z"/>
                        </svg>
                    {% elif message.tags == 'error' %}
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                             class="bi bi-exclamation-triangle-fill m-2" viewBox="0 0 16 16">
                            <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
                        </svg>
                    {% endif %}
                    <strong>{{ message }}</strong>
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endfor %}
        </section>
    {% endif %}
    <!--/.DJANGO MESSAGES-->
</header>

<!--MAIN CONTENT-->
<section class="main-content">
    {% block content %}

    {% endblock %}
</section>
<!--/.MAIN CONTENT-->

<!--NOTIFICATIONS-->
{% if user.is_authenticated and not user.is_superuser %}
    <!-- Div che verrà riempito con le notifiche-->
    <div class="toast-container" id="not-section"></div>

    <div style="position: fixed; bottom: 20px; right: 25px;">
        {% notifications_unread as unread_count %}
        <button class="btn btn-success position-relative p-2 rounded-circle
        {% if unread_count %}noti-animation{% endif %}"
                id="noti-button">
            <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-bell"
                 viewBox="0 0 16 16">
                <path d="M8 16a2 2 0 0 0 2-2H6a2 2 0 0 0 2 2zM8 1.918l-.797.161A4.002 4.002 0 0 0 4 6c0 .628-.134 2.197-.459 3.742-.16.767-.376 1.566-.663 2.258h10.244c-.287-.692-.502-1.49-.663-2.258C12.134 8.197 12 6.628 12 6a4.002 4.002 0 0 0-3.203-3.92L8 1.917zM14.22 12c.223.447.481.801.78 1H1c.299-.199.557-.553.78-1C2.68 10.2 3 6.88 3 6c0-2.42 1.72-4.44 4.005-4.901a1 1 0 1 1 1.99 0A5.002 5.002 0 0 1 13 6c0 .88.32 4.2 1.22 6z"/>
            </svg>

            <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-info">
                <!--Fetcha # di notifiche dal server con refresh di 15 sec-->
                {% live_notify_badge %}
                <span class="visually-hidden">unread messages</span>
            </span>
        </button>
    </div>
{% endif %}
<!--/.NOTIFICATIONS-->

<!--FOOTER-->
<footer class="container-fluid">
    <div class="container d-flex flex-wrap justify-content-around align-items-center pt-5">
        <a class="mb-5" href="{% url 'home' %}">
            <img src="{% static 'img/gym-logo.svg' %}"
                 class="logo_my_gym"
                 alt="logo my-gym">
        </a>
        <div class="d-flex align-items-top flex-wrap">
            <section class="p-4">
                <h3 class="c-white f-sm-bold text-uppercase">Dove siamo</h3>
                <br>
                <address class="c-grey-f f-slim">
                    V. Gorghetto 47 <br>
                    41030 Bomporto<br>
                    (Modena)<br>
                    P.IVA 0203 5440 198<br><br>
                    +33 059 891356 <br>
                </address>
            </section>
            <section class="p-4">
                <h3 class="c-white f-sm-bold text-uppercase">Orari di apertura</h3>
                <br>
                <address class="c-grey f-slim">
                    Lun/Ven:8.00-21.00 <br>
                    Sab:8.30-13.00<br>
                </address>
            </section>
        </div>
    </div>
    <div class="container-fluid legacy">
        <div class="container">
            <p class="f-slim c-grey-f">Copyrights 2023 &copy My Gym Palestra</p>
        </div>
    </div>
</footer>
<!--/.FOOTER-->


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous">
</script>


<script src="https://code.jquery.com/jquery-3.6.0.min.js"
        integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
        crossorigin="anonymous"
></script>

<script src="{% static 'notifications/notify.js' %}" type="text/javascript"></script>
{% load notifications_tags %}
{% register_notify_callbacks callbacks='fill_notification_list,fill_notification_badge' fetch=4 %}

<script>
    $(document).ready(function () {
        $("#noti-button").click(function () {
            let url = "{% url 'gym_user:load_notification' %}"
            $("#not-section").load(url, function (responseTxt, statusTxt, xhr) {
                if (statusTxt == "error")
                    alert("Error: " + xhr.status + ": " + xhr.statusText);
            });
            $("#not-section").toggle();
            $("#noti-toast").toast("show");
        });
    });
</script>

{% block scripts %}{% endblock %}

</body>

</html>

templates/my-gym/contacts.html
{% extends 'my-gym/base.html' %}
{% load static %}
{% block title %}Contatti - My-Gym{% endblock %}

{% block content %}
    <div class="container shadow p-3 mb-5 bg-body rounded">
        <h1 class="f-sm-bold m-3">Contattaci</h1>
        <div class="row m-3">
            <form class="col-sm-12 col-md-9 pb-sm-5 pb-md-0">
                <div class="mb-3">
                    <label for="exampleFormControlInput1" class="form-label">Il tuo indirizzo email</label>
                    <input type="email" class="form-control" id="exampleFormControlInput1"
                           placeholder="name@example.com">
                </div>
                <div class="mb-3">
                    <label for="exampleFormControlTextarea1" class="form-label">La tua richiesta</label>
                    <textarea class="form-control" placeholder="Scrivi la tua richiesta..."
                              id="exampleFormControlTextarea1" rows="3"></textarea>
                </div>
                <p class="text-end">
                    <btn class="btn btn-primary f-sm-bold">Invia</btn>
                </p>
            </form>
            <div class="col-sm-12 col-md-3">
                <address class="ps-3 c-grey-f f-mid">
                    V. Gorghetto 47 <br>
                    41030 Bomporto<br>
                    (Modena)<br>
                    P.IVA 0203 5440 198<br><br>
                    +33 059 891356 <br>
                    Lun/Ven:8.00-21.00 <br>
                    Sab:8.30-13.00<br>
                </address>
            </div>
        </div>
    </div>
{% endblock %}

templates/my-gym/gym.html
{% extends 'my-gym/base.html' %}
{% load static %}
{% block title %}Palestra - My-Gym{% endblock %}


{% block content %}
    <div class="container">
        <img src="{% static 'img/rodrigo-s-2mz9IKab7DE-unsplash.jpg' %}" style="width: 85%;">
        <h3 class="f-bold mt-5 text-uppercase mb-4">sala pesi</h3>
        <p class="f-slim c-grey">
            Tonificate e modellate il vostro corpo grazie alla Sala Isotonica: macchinari di ultima generazione vi
            offrono la possibilità di ottenere un allenamento particolarmente avanzato e volto al potenziamento del tono
            muscolare attraverso l’utilizzo di macchine specifiche per ogni distretto muscolare.

            La nostra Sala Pesi & Cardio risponde a qualsiasi vostra esigenza con una nuova e completa linea di
            attrezzature isotoniche in grado di combinare funzionalità e perfezione biomeccanica. La sala offre inoltre
            un’ampia sezione di macchine con pesi a carico libero, ideali per la coordinazione motoria generale e per
            sviluppare tutte le espressioni della forza e dell’ipertrofia.

            Gli istruttori di sala sono sempre a vostra disposizione per preparare schede di allenamento personalizzate,
            con un successivo supporto mirato e professionale per raggiungere gli obiettivi desiderati.
        </p>
    </div>
{% endblock %}

templates/my-gym/home.html
{% extends 'my-gym/base.html' %}
{% load static %}
{% block head %}
    <style>
        .cta {
            position: relative;
            background-image: url("{% static 'img/risen-wang-20jX9b35r_M-unsplash.jpg' %}");
            background-repeat: no-repeat;
            background-size: cover;
            background-position: center;
            width: 100%;
            opacity: 1;
            height: 80vh;
            margin: -90px 0 0 0 !important;
            padding: 0 !important;
            z-index: 0;
        }

        .intro {
            position: absolute;
            margin: auto;
            top: 0;
            left: 0;
            right: 0;
            bottom: 0;
            z-index: 1;
            width: 70%;
            height: 50%;
            text-align: center;
        }

        .name {
            color: #00a652;
            text-shadow: 0 0 3px #000000;
            font-size: 45px;
        }

        .name2 {
            color: #f4f4f4;
            text-shadow: 0 0 5px #000000;
            font-size: 60px
        }
    </style>
{% endblock %}
{% block title %}Home - My-Gym{% endblock %}


{% block content %}
    <section class="cta">
        <div class="intro">
            <span class="name text-uppercase f-sm-bold">My-Gym</span>
            <br>
            <span class="name2 text-uppercase f-mid">
                Esperti di fitness
            </span>
        </div>
    </section>
    <div class="container" style="margin-top: 100px;">
        <div class="row t">
            <div class="col-sm-12 col-md-4 mb-4 ps-5">
                <h3 class="f-sm-bold text-uppercase">Indirizzo</h3>
                <address class="c-grey mt-4">
                    V. Gorghetto 47 <br>
                    41030 Bomporto<br>
                    (Modena)<br>
                </address>
            </div>
            <div class="col-sm-12 col-md-4 mb-4 ps-5">
                <h3 class="f-sm-bold text-uppercase">Contatti</h3>
                <span class="d-flex mt-4">
                    <p class="c-grey me-2">Tel: </p>+33 059 891356
                </span>
            </div>
            <div class="col-sm-12 col-md-4 ps-5">
                <h3 class="f-sm-bold text-uppercase">Orari</h3>
                <span class="d-flex flex column c-grey mt-3">
                    Lun/Ven:8.00-21.00 <br>
                    Sab:8.30-13.00<br>
                </span>
            </div>
        </div>
    </div>
{% endblock %}

templates/my-gym/notifications.html
{% load static %}
{% for msg in noti %}
    <div class="toast fade show" role="alert" aria-live="assertive" aria-atomic="true"
         data-bs-autohide="false" id="noti-toast">
        <div class="toast-header d-flex justify-content-between p-0 bg-info">
            <img src="{% static 'img/gym-logo.svg' %}" class="rounded ms-3" width="50" height="40" alt="my-gym logo">
            <button type="button" class="btn-close me-3" data-bs-dismiss="toast" aria-label="Close"></button>
        </div>
        <div class="toast-body d-flex flex-column align-items-center">
            <p class="f-mid m-0 p-0">{{ msg.verb }}</p>
            <div class="mt-2 pt-2 border-top">
                <a type="button" href="{% url 'gym_course:courses' %}" class="btn btn-outline-primary btn-sm f-mid">
                    Affrettati iscriviti ora!
                </a>
                </a>
                <a type="button" class="btn btn-outline-secondary btn-sm f-mid"
                   href="{% url 'gym_course:mark_not_as_read'  msg.slug %}">
                    Segna come letto
                </a>
            </div>
        </div>
    </div>
{% empty %}
    <div class="toast fade show mb-4" role="alert" aria-live="assertive" aria-atomic="true"
         data-bs-autohide="false" id="noti-toast">
        <div class="toast-header d-flex justify-content-between p-0 bg-info">
            <img src="{% static 'img/gym-logo.svg' %}" class="rounded ms-3" width="60" height="50" alt="my-gym logo">
            <button type="button" class="btn-close me-3" data-bs-dismiss="toast" aria-label="Close"></button>
        </div>
        <div class="toast-body d-flex flex-column align-items-center">
            <p class="f-mid m-0 p-0">Nessuna notifica!</p>
        </div>
    </div>
{% endfor %}

templates/my-gym/services.html
{% extends 'my-gym/base.html' %}
{% load static %}
{% block head %}
    <style>
        .cta {
            background-image: url("{% static 'img/sven-mieke-MsCgmHuirDo-unsplash.jpg' %}");
            background-repeat: no-repeat;
            background-size: cover;
            background-position: center;
            width: 100%;
            height: 250px;
            margin: -90px 0 0 0 !important;
            padding: 0 !important;
        }
    </style>
{% endblock %}

{% block title %}Servizi - My-Gym{% endblock %}


{% block content %}
    <section class="cta"></section>
    <div class="container mt-5">
        <h3 class="f-sm-bold text-center text-uppercase mb-5">Fisioterapia</h3>
        <p class="c-grey f-slim mb-5 p-3">
            Per chi ne facesse richiesta sarà proponibile un vero e proprio percorso su misura per l’utente, anche
            individuando il tipo di recupero da raggiungere, sia esso rinforzo muscolare o stretching. Punto di forza è
            la stretta collaborazione fra istruttore della palestra, fisioterapista e medici, allo scopo di modificare i
            vari esercizi per adattarli alle esigenze del singolo, tenendo conto di eventuali limitazioni. I programmi
            terapeutici sono eseguiti da personale diplomato in terapia della riabilitazione
        </p>
        <hr>
        <h3 class="f-sm-bold text-center text-uppercase mb-5 mt-5">personal training</h3>
        <p class="c-grey f-slim mb-5 p-3">
            Il Club si avvale di un gruppo di qualificati PERSONAL TRAINERS per chi desideri avere un’assistenza
            continua e personalizzata durante l’intero allenamento; anche attraverso la collaborazione dello staff
            medico, il personal trainer ti aiuterà a:

            - individuare gli obiettivi da raggiungere;

            - scegliere il percorso da intraprendere per conseguirli, seguendo le tue necessità;

            Il personal trainer sarà un consulente, un allenatore, un amico che ti aiuterà a raggiungere i risultati da
            te prefissati. Contatta la segreteria per prenotare il tuo personal trainer.
        </p>
        <hr>
        <h3 class="f-sm-bold text-center text-uppercase mb-5 mt-5">pressoterapia</h3>
        <p class="c-grey f-slim mb-5 p-3">
            Procedura che mediante l’utilizzo di apposita apparecchiatura determina delle pressioni sugli arti inferiori
            che forniscono alle gambe leggerezza e sollievo e consentono il trattamento di: fasi iniziali di cattiva
            circolazione, insufficienza venosa, linfodrenaggio, cellulite, rottura capillari, distrofie della pelle.

            La pressoterapia è invece controindicata a coloro che soffrono di trombosi venosa profonda, infezioni degli
            arti inferiori e di insufficienza cardiaca grave
        </p>


    </div>
{% endblock %}