blog/urls.py
from django.urls import path
from .views import blog_post_create, blog_post_detail, BlogPostDelete, blog_post_list, BlogPostUpdate, filtered_posts
from .views import CategoryCreate, CategoryDelete, CategoryList

app_name = 'blog'

urlpatterns = [
    path('post-list/', blog_post_list, name='posts_list'),
    path('blogpost/create/', blog_post_create, name='post_creation'),
    path('blogpost/<int:pk>/delete/', BlogPostDelete.as_view(), name='post_delete'),
    path('blogpost/<int:pk>/detail/', blog_post_detail, name='post_detail'),
    path('blogpost/<int:pk>/update/', BlogPostUpdate.as_view(), name='post_update'),
    path('category/create/', CategoryCreate.as_view(), name='category_creation'),
    path('category/<int:pk>/delete/', CategoryDelete.as_view(), name='category_delete'),
    path('category-list/', CategoryList.as_view(), name='category_list'),
    path('find/<str:name>/', filtered_posts, name='filter')
]

core/urls.py
import notifications.urls
from django.contrib import admin
from django.urls import include, path, re_path
from core.views import Home, Contacts, Gym, Services
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^$', Home.as_view(), name='home'),
    path('palestra/', Gym.as_view(), name='gym'),
    path('servizi/', Services.as_view(), name='services'),
    path('corsi/', include('gym_course.urls')),
    path('contattaci/', Contacts.as_view(), name='contacts'),
    path('blog/', include('blog.urls')),
    path('blog/blogpost/', include('comment.urls')),
    path('user/', include('gym_user.urls')),
    path('rooms/', include('room.urls')),
    path('auth/', include('user_auth.urls')),
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),
]

"""
By doing this, Django development server can able to serve the media
files during development mode when setting  DEBUG = TRUE  in settings.py file.
"""
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user_auth/urls.py
from django.urls import path
from .views import change_password, change_user_data, delete_user, login_user, logout_user, register
app_name = 'user_auth'

urlpatterns = [
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('register/', register, name='register'),
    path('change_password/', change_password, name='change_password'),
    path('change_user_data/', change_user_data, name='change_data'),
    path('delete_user/', delete_user, name='user_delete'),
]

blog/models.py
from django.db import models


class Category(models.Model):

    name = models.CharField(max_length=30, blank=False, unique=True, verbose_name="Nome")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Categorie'


class BlogPost(models.Model):

    title = models.CharField(max_length=100)
    blog_img = models.ImageField(upload_to='blog-img-upload')
    content = models.TextField()
    date = models.DateField(auto_now=True)
    category = models.ManyToManyField(Category)

    def __str__(self):
        return self.title

    @property
    def image_url(self):
        if self.blog_img and hasattr(self.blog_img, 'url'):
            return self.blog_img.url

    class Meta:
        ordering = ('-date',)
        verbose_name_plural = 'Posts'

blog/forms.py
from django.forms import ModelForm
from blog.models import BlogPost, Category
from django.utils.translation import gettext_lazy as _
from django import forms


class BlogPostCreateForm(ModelForm):
    class Meta:
        model = BlogPost
        fields = ('title', 'blog_img', 'content', 'category')
        labels = {
            'title': _('Titolo'),
            'blog_img': _('Immagine del post'),
            'content': _('Contenuto'),
            'category': _('Categoria')
        }

blog/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib import messages
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, DeleteView, ListView, UpdateView
from blog.forms import BlogPostCreateForm
from blog.models import BlogPost, Category
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin

from comment.forms import CommentForm


class CategoryCreate(PermissionRequiredMixin, SuccessMessageMixin, CreateView):
    model = Category
    fields = "__all__"
    template_name = "category/category_creation.html"
    success_url = reverse_lazy("gym_user:profile")

    permission_required = "blog.add_category"
    raise_exception = True
    success_message = "Categoria creata correttamente!"


class CategoryDelete(PermissionRequiredMixin, SuccessMessageMixin, DeleteView):
    model = Category
    template_name = "category/category_delete.html"
    success_url = reverse_lazy("gym_user:profile")

    permission_required = "blog.delete_category"
    raise_exception = True
    success_message = "Categoria eliminata correttamente!"


class CategoryList(PermissionRequiredMixin, ListView):
    model = Category
    template_name = "category/category_list.html"
    context_object_name = "categorylist"

    permission_required = "blog.view_category"
    raise_exception = True


@permission_required("blog.add_blogpost", raise_exception=True)
def blog_post_create(request):
    if request.method == "POST":
        form = BlogPostCreateForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, "Post creato correttamente!")
            return redirect("gym_user:profile")
    else:
        form = BlogPostCreateForm()

    ctx = {"warning": "Crea almeno una categoria prima di inserire un post",
           "categories": Category.objects.all(),
           "tot_cat": Category.objects.count(),
           "form": form}

    temp = "blog/post_creation.html"
    return render(request, temp, ctx)


class BlogPostDelete(PermissionRequiredMixin, SuccessMessageMixin, DeleteView):
    model = BlogPost
    template_name = "blog/post_delete.html"
    success_url = reverse_lazy("gym_user:profile")

    permission_required = "blog.delete_blogpost"
    raise_exception = True
    success_message = "Post eliminato correttamente!"


class BlogPostUpdate(PermissionRequiredMixin, UpdateView):
    model = BlogPost
    form_class = BlogPostCreateForm
    template_name = "blog/post_update.html"

    permission_required = "blog.change_blogpost"
    raise_exception = True

    def get_success_url(self):
        pk = self.get_context_data()["object"].pk
        messages.success(self.request, 'Post aggiornato correttamente!')
        return reverse_lazy("gym_user:profile")


def blog_post_detail(request, pk):
    blog_post = get_object_or_404(BlogPost, pk=pk)
    temp = "blog/post_detail.html"

    ctx = {"post": blog_post,
           "categories": Category.objects.all(),
           "last_articles": BlogPost.objects.all().order_by('-date')[:5]}

    if request.user.is_authenticated:
        if request.method == "POST":
            form = CommentForm(request.POST)
            if form.is_valid():
                comment = form.save(commit=False)
                comment.post = blog_post
                comment.commenter = request.user
                comment.save()
                messages.success(request, "Messaggio postato correttamente!")
                return HttpResponseRedirect(reverse("blog:post_detail", kwargs={'pk': pk}))
        else:
            form = CommentForm()

        ctx.update({"comment_form": form})

        return render(request, temp, ctx)

    return render(request, temp, ctx)


def blog_post_list(request):
    blogposts = BlogPost.objects.all()
    categories = Category.objects.all()
    tot_posts = BlogPost.objects.all().count()
    return render(request,
                  "blog/posts_list.html",
                  {"blogposts": blogposts,
                   "categories": categories,
                   "tot_post": tot_posts})


def filtered_posts(request, name):
    if name == "all":
        posts = BlogPost.objects.all()
    else:
        posts = BlogPost.objects.filter(category__name__contains=name)
    return render(request, "blog/filtered_posts.html", {"blogposts": posts})

templates/blog/filtered_posts.html
{% load static %}
{% for post in blogposts %}
    <div class="col-sm-12 col-lg-6 mt-5" id="card">
        <div class="card" style="width: 28rem; width: 100%;">
            <img src="{{ post.image_url }}" class="card-img-top" alt="{{ post.title }}">
            <div class="card-body">
                <h5 class="card-title text-uppercase f-sm-bold">{{ post.title }}</h5>
                <p class="card-text">{{ post.content | truncatechars:50 }}</p>
                <a href="{% url 'blog:post_detail' post.id %}" class="btn btn-primary f-sm-bold">Scopri di
                    più</a>
            </div>
        </div>
    </div>
{% endfor %}

templates/blog/last_articles.html
{% for art in last_articles %}

    <div class="d-flex flex-row justify-content-around align-items-center flex-wrap">
        <img src="{{ art.image_url }}"
             class="aside_art_img rounded img-fluid"
             alt="post-image">
        <div class="d-flex flex-column m-1">
            <h7 class="f-bold text-uppercase">{{ art.title|truncatechars:10 }}</h7>

            {{ art.content|truncatechars:10 }}
        </div>
        <a href="{% url 'blog:post_detail' art.id %}" class="m-1">
            <span class="badge bg-primary">Leggi!</span>
        </a>
    </div>
    <hr>
{% endfor %}

templates/blog/post_creation.html
{% extends 'my-gym/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block head %}
    <style>
        form {
            max-width: 75% !important;
            margin: 0 auto;
        }

        form input {
            margin: 17px 0 !important;
        }

        form label {
            font-size: 14px;
            font-weight: bold;
            margin: 5px 0 !important;
            padding: 5px;
        }

    </style>
{% endblock %}
{% block title %}Post : Creazione{% endblock %}

{% block content %}
    {% if tot_cat == 0 %}
        <div class="container alert alert-warning d-flex align-items-center justify-content-center" role="alert">
            <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor"
                 class="bi bi-exclamation-triangle-fill m-3" viewBox="0 0 16 16">
                <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
            </svg>
            <p class="m-0 p-0 f-sm-bold">{{ warning }}</p>
        </div>
        <p class="text-center">
            <a href="{% url 'blog:category_creation' %}" class="link-info">Aggiungi una categoria</a>
        </p>
    {% else %}
        <div class="d-flex flex-column text-center">
            <h3 class="f-sm-bold mb-5">Crea il tuo post:</h3>
            <form method="POST" enctype="multipart/form-data" class=" shadow-sm p-3 mb-5 bg-body rounded">
                {% csrf_token %}
                {{ form|crispy }}
                <div class="d-grid gap-2 mt-4">
                    <button class="btn btn-primary f-sm-bold" type="submit">Crea post</button>
                </div>
            </form>

        </div>
    {% endif %}
{% endblock %}

templates/blog/post_delete.html
{% extends 'my-gym/base.html' %}
{% load static %}
{% block title %}Post : {{ object.title }}{% endblock %}

{% block content %}
    <form method="post" class="">{% csrf_token %}
        <div class="container alert alert-warning d-flex align-items-center" role="alert">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor"
                 class="bi bi-exclamation-triangle-fill flex-shrink-0 me-2" viewBox="0 0 16 16" role="img"
                 aria-label="Warning:">
                <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
            </svg>
            <div>
                Sei sicuro di voler eliminare "{{ object }}" ?
            </div>
        </div>
        <p class="text-center ">
            <button type="submit" class="btn btn-primary f-sm-bold">Conferma</button>
        </p>
    </form>
{% endblock %}

templates/blog/post_detail.html
{% extends 'my-gym/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block head %}
    <link href="{% static 'css/blog/blog-styles.css' %}"
          rel="stylesheet"
          type="text/css">
    <style>
        label {
            display: none;
        }
    </style>
{% endblock %}
{% block title %}Post : {{ post.title|capfirst }}{% endblock %}


{% block content %}

    <article class="container shadow p-3 mb-5 bg-body rounded" id="post">
        <section class="row">
            <div class="col-sm-8">
                <img src="{{ post.image_url }}" class="blog_img" width="100%" alt="post-image">
                <br><br>
                <h1 class="f-bold mt-1 mb-4">{{ post.title|capfirst }}</h1>
                <h6 class="f-mid mt-1 mb-2">{{ post.date|date:"SHORT_DATE_FORMAT" }}</h6>
                <div class="d-flex flex-row">
                    {% for cat in post.category.all %}
                        <h6><span class="badge bg-info text-dark me-2">{{ cat }}</span></h6>
                    {% endfor %}
                </div>
                <p class="c-grey" style="word-wrap:break-word">{{ post.content }}</p>
            </div>

            <aside class="col-sm-4 categories">
                <h7 class="f-bold">CATEGORIE</h7>
                <hr>
                <ul class="list-group list-group-flush">
                    {% for cat in categories %}
                        <li class="list-group-item">{{ cat|capfirst }}</li>
                    {% endfor %}
                </ul>
                <div class="last_arts">
                    <h7 class="f-bold">ULTIMI ARTICOLI</h7>
                    <hr>
                    {% include "blog/last_articles.html" %}
                </div>
            </aside>
        </section>
        <div class="container">
            <hr>
        </div>
        <!-- BLOCCO COMMENTI-->
        <section class="m-0 d-flex flex-column justify-content-center">
            <div class="d-flex flex-row justify-content-around justify-content-center mt-3 mb-2">
                <div class="mb-2">
                    <img src="{% static 'img/chatboxes.png' %}" alt="comment_image" class="chat-img">
                    <a class="f-mid c-grey" id="to_comment">Commenti</a>
                </div>
                {% if user.is_authenticated %}
                    <div class="position-relative f-sm-bold" id="add_msg"  style="display: none;">
                        <a href="#to_write">
                            <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor"
                                 class="bi bi-chat" viewBox="0 0 16 16">
                                <path d="M2.678 11.894a1 1 0 0 1 .287.801 10.97 10.97 0 0 1-.398 2c1.395-.323 2.247-.697 2.634-.893a1 1 0 0 1 .71-.074A8.06 8.06 0 0 0 8 14c3.996 0 7-2.807 7-6 0-3.192-3.004-6-7-6S1 4.808 1 8c0 1.468.617 2.83 1.678 3.894zm-.493 3.905a21.682 21.682 0 0 1-.713.129c-.2.032-.352-.176-.273-.362a9.68 9.68 0 0 0 .244-.637l.003-.01c.248-.72.45-1.548.524-2.319C.743 11.37 0 9.76 0 8c0-3.866 3.582-7 8-7s8 3.134 8 7-3.582 7-8 7a9.06 9.06 0 0 1-2.347-.306c-.52.263-1.639.742-3.468 1.105z"/>
                            </svg>
                            <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-primary">
                            1+
                          </span>
                        </a>
                    </div>
                {% endif %}
            </div>
            <section id="comments"
                     class="overflow-auto"
                     style="max-height: 500px; display: none; margin-bottom: 150px;">
                {% include 'comment/post_comments.html' %}
            </section>
            <!--./BLOCCO COMMENTI-->
        </section>
        {% if user.is_authenticated %}
            <section class="container border-top border-info bg-light"
                     id="to_write"
                     style="position: relative; width: 100%; display: none;">
                <form method="POST" class="pt-3 text-end" style="margin-top: 100px;">
                    {% csrf_token %}
                    {{ comment_form|crispy }}
                    <button type="submit" class="bg-transparent border-0 mt-2 me-2" id="send_msg">
                        <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18"
                             fill="currentColor"
                             class="bi bi-send" viewBox="0 0 16 16"
                             style="transform: rotate(45deg)">
                            <path d="M15.854.146a.5.5 0 0 1 .11.54l-5.819 14.547a.75.75 0 0 1-1.329.124l-3.178-4.995L.643 7.184a.75.75 0 0 1 .124-1.33L15.314.037a.5.5 0 0 1 .54.11ZM6.636 10.07l2.761 4.338L14.13 2.576 6.636 10.07Zm6.787-8.201L1.591 6.602l4.339 2.76 7.494-7.493Z"/>
                        </svg>
                    </button>
                </form>
            </section>
        {% else %}
            <p class="text-center mt-4" id="user_info" style="display: none;">
                <a href="{% url 'user_auth:login' %}" class="link-primary text-center">Accedi per
                    scrivere un commento!</a>
            </p>
        {% endif %}
    </article>

{% endblock %}
{% block scripts %}
    <script>
        $(document).ready(function () {
            $("#to_comment").click(function () {
                $("#comments").toggle();
                $("#add_msg").toggle();
                $("#to_write").toggle();
                $("#user_info").toggle();
            });
        });
    </script>
{% endblock %}

templates/blog/post_update.html
{% extends 'my-gym/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block head %}
    <style>
        form {
            max-width: 75% !important;
            margin: 0 auto;
        }

        form input {
            margin: 17px 0 !important;
        }

        form label {
            font-size: 14px;
            font-weight: bold;
            margin: 5px 0 !important;
            padding: 5px;
        }

    </style>
{% endblock %}
{% block title %}Post : {{ object.title }}{% endblock %}

{% block content %}

    <h4 class="text-center f-sm-bold">Modifica il tuo post:</h4>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <div class="d-grid gap-2 mt-4">
            <button class="btn btn-primary f-sm-bold" type="submit">Modifica post</button>
        </div>
    </form>

{% endblock %}

templates/blog/posts_list.html
{% extends 'my-gym/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block head %}
    <link href="{% static 'css/blog/blog-styles.css' %}" rel="stylesheet" type="text/css">
{% endblock %}
{% block title %}Blog - My-Gym{% endblock %}

{% block content %}
    {% if tot_post == 0 %}
        <div class="container alert alert-primary d-flex align-items-center justify-content-center" role="alert">
            <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor"
                 class="bi bi-info-circle-fill m-2" viewBox="0 0 16 16">
                <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2z"/>
            </svg>
            <div class="f-sm-bold">
                Nessun post creato!
            </div>
        </div>
    {% else %}
        <!--FORM-->
        <div class="container d-flex bd-highlight shadow-sm p-3 mb-5 bg-body rounded">
            <label for="cat-selector" class="text-primary f-sm-bold text-uppercase bd-highlight p-1"
                   style="font-size: 14px; letter-spacing: -0.5px">
                Filtra per categoria:
            </label>
            <div class="ms-auto bd-highlight">
                <select id="cat-selector" class="form-select form-select-sm ms-auto" aria-label="category selector"
                        onchange="selectCat()">
                    {% for c in categories %}
                        <option value="{{ c.name }}">{{ c.name }}</option>
                    {% endfor %}
                    <option value="all" selected>Vedi tutte</option>
                </select>
            </div>
        </div>
        <!--./-FORM-->
        <div class="container">
            <div class="row shadow-sm p-3 mb-5 bg-body rounded" id="to-fill">
                {% for post in blogposts %}
                    <div class="col-sm-12 col-lg-6 mt-5" id="card">
                        <div class="card" style="width: 28rem;">
                            <img src="{{ post.image_url }}" class="card-img-top" alt="{{ post.title }}" loading="lazy">
                            <div class="card-body">
                                <h5 class="card-title text-uppercase f-sm-bold">{{ post.title }}</h5>
                                <p class="card-text">{{ post.content | truncatechars:50 }}</p>
                                <a href="{% url 'blog:post_detail' post.id %}" class="btn btn-primary f-sm-bold">Scopri
                                    di
                                    più</a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    {% endif %}
{% endblock %}

{% block scripts %}
    <script>
        function selectCat() {
            let choose = document.getElementById("cat-selector").value;
            let url = "{% url 'blog:filter' name="name" %}".replace("name", choose)
            $("#to-fill").load(url, function (responseTxt, statusTxt, xhr) {
                if (statusTxt == "error")
                    alert("Error: " + xhr.status + ": " + xhr.statusText);
            });
        }
    </script>
{% endblock %}