blog/urls.py
from django.urls import path
from .views import blog_post_create, blog_post_detail, BlogPostDelete, blog_post_list, BlogPostUpdate, filtered_posts
from .views import CategoryCreate, CategoryDelete, CategoryList

app_name = 'blog'

urlpatterns = [
    path('post-list/', blog_post_list, name='posts_list'),
    path('blogpost/create/', blog_post_create, name='post_creation'),
    path('blogpost/<int:pk>/delete/', BlogPostDelete.as_view(), name='post_delete'),
    path('blogpost/<int:pk>/detail/', blog_post_detail, name='post_detail'),
    path('blogpost/<int:pk>/update/', BlogPostUpdate.as_view(), name='post_update'),
    path('category/create/', CategoryCreate.as_view(), name='category_creation'),
    path('category/<int:pk>/delete/', CategoryDelete.as_view(), name='category_delete'),
    path('category-list/', CategoryList.as_view(), name='category_list'),
    path('find/<str:name>/', filtered_posts, name='filter')
]

core/urls.py
import notifications.urls
from django.contrib import admin
from django.urls import include, path, re_path
from core.views import Home, Contacts, Gym, Services
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^$', Home.as_view(), name='home'),
    path('palestra/', Gym.as_view(), name='gym'),
    path('servizi/', Services.as_view(), name='services'),
    path('corsi/', include('gym_course.urls')),
    path('contattaci/', Contacts.as_view(), name='contacts'),
    path('blog/', include('blog.urls')),
    path('blog/blogpost/', include('comment.urls')),
    path('user/', include('gym_user.urls')),
    path('rooms/', include('room.urls')),
    path('auth/', include('user_auth.urls')),
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),
]

"""
By doing this, Django development server can able to serve the media
files during development mode when setting  DEBUG = TRUE  in settings.py file.
"""
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gym_course/urls.py
from django.urls import path
from .views import add_to_queue, courses_list, make_inscription, mark_as_read, unsubscribe
app_name = 'gym_course'

urlpatterns = [
    path('', courses_list, name='courses'),
    path('iscriviti/<int:course_pk>/', make_inscription, name='make_inscription'),
    path('mettiti-in-lista/<int:course_pk>/', add_to_queue, name='add_to_queue'),
    path('discriviti/<int:course_pk>/<str:to_queue>/', unsubscribe, name='unsubscribe'),
    path('mark-as-read/<int:not_slug>/', mark_as_read, name='mark_not_as_read'),
]

user_auth/urls.py
from django.urls import path
from .views import change_password, change_user_data, delete_user, login_user, logout_user, register
app_name = 'user_auth'

urlpatterns = [
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('register/', register, name='register'),
    path('change_password/', change_password, name='change_password'),
    path('change_user_data/', change_user_data, name='change_data'),
    path('delete_user/', delete_user, name='user_delete'),
]

gym_course/models.py
from django.db import models
from gym_user.models import GymUser


class WaitingQueue(models.Model):
    name = models.CharField(max_length=50)
    queue_subs = models.ManyToManyField(GymUser, related_name="usr_queue", blank=True)

    def __str__(self):
        return "Lista d'attesa di " + self.name

    def get_tot_subs(self):
        return self.queue_subs.objects.all().count()

    class Meta:
        verbose_name_plural = 'Liste di attesa'


class GymCourse(models.Model):
    title = models.CharField(max_length=50)
    description = models.TextField()
    subs = models.ManyToManyField(GymUser, related_name="subscribers", blank=True)
    queue = models.OneToOneField(WaitingQueue, related_name="course_queue", on_delete=models.CASCADE)
    date_of_start = models.DateField()
    tot_sub = models.PositiveSmallIntegerField()
    capacity = models.PositiveSmallIntegerField()

    def __str__(self):
        return "Corso di " + self.title

    class Meta:
        ordering = ('title',)
        verbose_name_plural = 'Corsi'

gym_course/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
from notifications.models import Notification
from notifications.utils import slug2id
from .models import GymCourse
from gym_user.models import GymUser


def courses_list(request):
    crs = GymCourse.objects.all()
    return render(request, "gym_course/courses.html", {"courses": crs})


@login_required(login_url="user_auth:login")
def make_inscription(request, course_pk):
    if request.method == 'GET':
        crs = get_object_or_404(GymCourse, pk=course_pk)
        usr = get_object_or_404(GymUser, pk=request.user.pk)
        if usr in crs.subs.all():
            messages.warning(request,
                             "Sei già iscritto/a al corso di {corso}, entra nella tua area personale per vedere i "
                             "dettagli!".format(corso=crs.title.capitalize()))

        elif usr not in crs.subs.all() and crs.capacity > 0:
            if usr in crs.queue.queue_subs.all():
                crs.queue.queue_subs.remove(usr)
                messages.success(request,
                                 "Sei stato/a iscritto/a al corso di {corso}, e discritto alla sua coda d'attesa "
                                 "entra nella tua area personale per vedere i "
                                 "dettagli!".format(corso=crs.title.capitalize()))
            else:
                messages.success(request,
                                 "Sei stato/a iscritto/a al corso di {corso}, entra nella tua area personale per "
                                 "vedere i "
                                 "dettagli!".format(corso=crs.title.capitalize()))
            crs.subs.add(usr)
            crs.tot_sub += 1
            crs.capacity -= 1
            crs.save()

    return redirect("gym_course:courses")


@login_required(login_url="user_auth:login")
def add_to_queue(request, course_pk):
    if request.method == 'GET':
        crs = get_object_or_404(GymCourse, pk=course_pk)
        usr = get_object_or_404(GymUser, pk=request.user.pk)
        if usr in crs.subs.all():
            messages.warning(request,
                             "Sei gia iscritto/a al corso di {corso}, entra nella tua pagina personale per vedere i "
                             "dettagli!".format(corso=crs.title.capitalize()))
        elif usr not in crs.subs.all():
            crs.queue.queue_subs.add(usr)
            crs.save()
            messages.success(request,
                             "Sei stato/a inserito/a nella lista d'attesa del corso di {corso}, "
                             "riceverai un messaggio quando si libererà un posto!".format(corso=crs.title.capitalize()))

    return redirect("gym_course:courses")


@login_required(login_url="user_auth:login")
def unsubscribe(request, course_pk, to_queue):
    if request.method == 'POST':
        crs = get_object_or_404(GymCourse, pk=course_pk)
        usr = get_object_or_404(GymUser, pk=request.user.pk)

        if to_queue == "False":
            crs.subs.remove(usr)
            crs.tot_sub -= 1
            crs.capacity += 1
            crs.save()
            messages.success(request,
                             "Sei stato/a disiscritto dal corso di {corso}!".format(corso=crs.title.capitalize()))
        else:
            crs.queue.queue_subs.remove(usr)
            crs.save()
            messages.success(request, "Sei stato/a disiscritto dalla lista di attesa del corso di {corso}!".format(
                corso=crs.title.capitalize()))

    return redirect("gym_user:profile")


@login_required(login_url="user_auth:login")
def mark_as_read(request, not_slug):
    if request.method == 'GET':
        # utility che converte lo slug dell' entry notifica nel suo id
        not_id = slug2id(not_slug)
        noti = get_object_or_404(Notification, recipient=request.user, id=not_id)

        noti.mark_as_read()  # leggo la notifica
        noti.delete()  # elimino la notifica
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

templates/gym_course/courses.html
{% extends 'my-gym/base.html' %}
{% load static %}
{% block title %}Corsi - My-Gym{% endblock %}
{% block content %}
    {% for crs in courses %}
        <div class="container">
            <div class="shadow p-3 mb-5 bg-body rounded mb-4 d-flex flex-column flex-md-row align-items-center justify-content-between">
                <div class="p-4 text-center text-md-start">
                    <h2 class="f-sm-bold mb-5">Corso di {{ crs.title|capfirst }}</h2>
                    <p class="mb-5">{{ crs.description }}</p>
                    <h6>Aperture iscrizioni: {{ crs.date_of_start|date:"SHORT_DATE_FORMAT" }}</h6>
                    {% if crs.capacity == 0 %}
                        <h6 class="text-danger mb-3 f-sm-bold">Posti esauriti per questo corso!</h6>
                        {% if request.user not in crs.queue.queue_subs.all %}
                            <form method="GET" action="{% url 'gym_course:add_to_queue' crs.pk %}">
                                <button style="" type="submit" class="btn btn-link c-grey f-slim p-0">
                                    Iscriviti alla lista d'attesa per partecipare al corso di {{ crs.title|capfirst }}
                                </button>
                            </form>
                        {% else %}
                            <p class="c-grey f-slim">Sei attualmente iscritto alla lista d'attesa, riceverai un
                                messaggio
                                appena si libererà un posto.</p>
                        {% endif %}
                    {% else %}
                        <h6>Posti disponibili: {{ crs.capacity }}</h6>
                    {% endif %}
                    {% if not user.is_authenticated %}
                        <a href="{% url 'user_auth:login' %}" class="link-secondary">
                            <small style="font-size: 10px;" class="f-bold text-decoration-underline">
                                Accedi per iscriverti al corso!
                            </small>
                        </a>
                    {% endif %}
                </div>
                <div class="pe-md-5">
                    <form method="GET" action="{% url 'gym_course:make_inscription' crs.pk %}">
                        <div class="d-grid gap-2">
                            <button type="button submit" class="btn btn-primary f-sm-bold"
                                    {% if crs.capacity == 0 or not user.is_authenticated %}
                                    disabled
                                    {% endif %}
                            >
                                Iscriviti
                            </button>
                        </div>
                    </form>
                </div>
            </div>
            {% empty %}
            <div class="container alert alert-primary d-flex align-items-center justify-content-center" role="alert">
                <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor"
                     class="bi bi-info-circle-fill m-2" viewBox="0 0 16 16">
                    <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2z"/>
                </svg>
                <div class="f-sm-bold">
                    La palestra, attualmente, non fornisce nessun corso...
                </div>
            </div>
        </div>
    {% endfor %}

{% endblock %}